import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../core/theme/app_theme.dart';
import '../../../shared/services/caregiver_service.dart';
import '../../../shared/services/gemini_service.dart';
import '../../../shared/services/patient_service.dart';

/// Daily AI-generated health summary + weekly trend report for caregivers.
/// Uses fl_chart for mood and pain bar charts. MD3 layout, ≥16px fonts.
class ReportsScreen extends StatefulWidget {
  final String? patientId;

  const ReportsScreen({super.key, this.patientId});

  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends State<ReportsScreen> {
  static const List<String> _dayLabels = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];

  bool _isGeneratingPDF = false;

  /// Cached patient future - shared by all FutureBuilders so Firestore is
  /// only queried once per screen load.
  late final Future<PatientProfile?> _patientFuture = _loadPatient();

  Future<PatientProfile?> _loadPatient() async {
    // If patientId is provided via route, use it
    if (widget.patientId != null && widget.patientId!.isNotEmpty) {
      return await PatientService.instance.getPatientById(widget.patientId!);
    }

    // Otherwise, get the first patient assigned to this caregiver
    final profile =
        await CaregiverService.instance.getCurrentCaregiverProfile();
    if (profile == null) return null;
    final patients = await PatientService.instance.getPatientsByCaregiver(
      profile.id,
    );
    return patients.isNotEmpty ? patients.first : null;
  }

  static String _getDateRangeLabel() {
    final now = DateTime.now();
    final start = now.subtract(const Duration(days: 6));
    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    if (start.month == now.month) {
      return '${months[start.month - 1]} ${start.day} – ${now.day}, ${now.year}';
    }
    return '${months[start.month - 1]} ${start.day} – ${months[now.month - 1]} ${now.day}, ${now.year}';
  }

  Future<void> _generateAndSharePDF() async {
    if (_isGeneratingPDF) return;
    setState(() => _isGeneratingPDF = true);

    try {
      final patient = await _patientFuture;
      if (patient == null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Error: No patient found')),
          );
        }
        return;
      }

      final patientName = patient.name;
      final stats = await PatientService.instance.getWeeklyStats(patient.id);

      // Generate text report
      final now = DateTime.now();
      final dateStr = 'Mar ${now.day - 6} – Apr ${now.day}, ${now.year}';

      final reportText = '''
📋 Daily Health Summary
$patientName's Health Trends

Period: $dateStr

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 Today's Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Check-ins: ${stats['checkins']}
💊 Medication Adherence: ${stats['adherence']}
🩹 Average Pain: ${stats['avgPain']}
🚨 SOS Alerts: ${stats['sosAlerts']}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by CareSync AI
${DateTime.now().toString().split('.').first}

This report summarizes the weekly health metrics 
and trends for the patient. Please consult with 
healthcare providers for medical advice.
''';

      // Show in a dialog that can be copied
      if (mounted) {
        showDialog(
          context: context,
          builder:
              (context) => AlertDialog(
                title: const Text('Health Report'),
                content: SingleChildScrollView(
                  child: Text(
                    reportText,
                    style: const TextStyle(fontFamily: 'monospace'),
                  ),
                ),
                actions: [
                  TextButton(
                    onPressed: () => Navigator.pop(context),
                    child: const Text('Close'),
                  ),
                  TextButton(
                    onPressed: () {
                      Clipboard.setData(ClipboardData(text: reportText));
                      Navigator.pop(context);
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text('Report copied to clipboard'),
                        ),
                      );
                    },
                    child: const Text('Copy'),
                  ),
                ],
              ),
        );
      }
    } catch (e) {
      debugPrint('Error generating report: $e');
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: ${e.toString()}')));
      }
    } finally {
      if (mounted) {
        setState(() => _isGeneratingPDF = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded),
          onPressed: () => context.pop(),
        ),
        title: Text(
          'Health Report',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: Theme.of(context).textTheme.bodyLarge?.color,
          ),
        ),
        actions: [
          TextButton.icon(
            onPressed: _isGeneratingPDF ? null : _generateAndSharePDF,
            icon:
                _isGeneratingPDF
                    ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                    : const Icon(Icons.ios_share_rounded, size: 16),
            label: Text(
              _isGeneratingPDF ? 'Generating...' : 'Share',
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 8),
        ],
        surfaceTintColor: Colors.transparent,
        elevation: 0,
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(20, 20, 20, 40),
        children: [
          // ── Page header ────────────────────────────────────────────────
          Text(
            _getDateRangeLabel(),
            style: GoogleFonts.inter(
              fontSize: 13,
              color: AppTheme.textLight,
              fontWeight: FontWeight.w500,
            ),
          ),
          const SizedBox(height: 4),
          FutureBuilder<PatientProfile?>(
            future: _patientFuture,
            builder: (context, snapshot) {
              final patientName = snapshot.data?.name ?? 'Patient';
              return Text(
                "$patientName's Health Trends",
                style: GoogleFonts.inter(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  color: AppTheme.textDark,
                ),
              );
            },
          ),
          const SizedBox(height: 20),

          // ── AI narrative ───────────────────────────────────────────────
          FutureBuilder<PatientProfile?>(
            future: _patientFuture,
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return _buildNarrativeShimmer();
              }
              final patient = snapshot.data;
              if (patient == null) {
                return const _AiNarrativeCard(
                  narrative: 'No patient data available.',
                );
              }
              return _AiNarrativeLoader(
                patientId: patient.id,
                patientName: patient.name,
              );
            },
          ),
          const SizedBox(height: 20),

          // ── Weekly stats ───────────────────────────────────────────────
          _SectionHeader(title: 'Weekly Overview'),
          const SizedBox(height: 10),
          FutureBuilder<PatientProfile?>(
            future: _patientFuture,
            builder: (context, patientSnap) {
              if (patientSnap.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }
              final patient = patientSnap.data;
              if (patient == null) {
                return const _WeeklyStatsGrid(
                  checkins: '0 / 7',
                  adherence: '0%',
                  avgPain: '0 / 10',
                  sosAlerts: '0',
                );
              }
              return FutureBuilder<Map<String, dynamic>>(
                future: PatientService.instance.getWeeklyStats(patient.id),
                builder: (context, statsSnap) {
                  if (statsSnap.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  final s = statsSnap.data ?? {};
                  return _WeeklyStatsGrid(
                    checkins: s['checkins'] ?? '0 / 7',
                    adherence: s['adherence'] ?? '0%',
                    avgPain: s['avgPain'] ?? '0 / 10',
                    sosAlerts: s['sosAlerts'] ?? '0',
                  );
                },
              );
            },
          ),
          const SizedBox(height: 20),

          // ── Mood trend chart ───────────────────────────────────────────
          _SectionHeader(title: '7-Day Mood Trend'),
          const SizedBox(height: 4),
          Text(
            'Daily mood score (1 = bad, 5 = great)',
            style: GoogleFonts.inter(fontSize: 13, color: AppTheme.textMid),
          ),
          const SizedBox(height: 10),
          FutureBuilder<PatientProfile?>(
            future: _patientFuture,
            builder: (context, patientSnap) {
              if (patientSnap.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }
              final patient = patientSnap.data;
              if (patient == null) {
                return _BarChartCard(
                  data: List.filled(7, 0),
                  dayLabels: _dayLabels,
                  maxY: 5,
                  barColor: AppTheme.accentGreen,
                  gradientColors: [
                    AppTheme.accentGreen,
                    const Color(0xFF4ADE80),
                  ],
                  tooltipSuffix: '/5',
                  yAxisLabel: _moodYLabel,
                );
              }
              return FutureBuilder<Map<String, List<double>>>(
                future: PatientService.instance.getWeeklyMoodPainTrends(
                  patient.id,
                ),
                builder: (context, trendsSnap) {
                  if (trendsSnap.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  final moodData =
                      trendsSnap.data?['mood'] ?? List.filled(7, 0);
                  return _BarChartCard(
                    data: moodData,
                    dayLabels: _dayLabels,
                    maxY: 5,
                    barColor: AppTheme.accentGreen,
                    gradientColors: [
                      AppTheme.accentGreen,
                      const Color(0xFF4ADE80),
                    ],
                    tooltipSuffix: '/5',
                    yAxisLabel: _moodYLabel,
                  );
                },
              );
            },
          ),
          const SizedBox(height: 20),

          // ── Pain trend chart ───────────────────────────────────────────
          _SectionHeader(title: '7-Day Pain Trend'),
          const SizedBox(height: 4),
          Text(
            'Daily reported pain (0 = none, 10 = severe)',
            style: GoogleFonts.inter(fontSize: 13, color: AppTheme.textMid),
          ),
          const SizedBox(height: 10),
          FutureBuilder<PatientProfile?>(
            future: _patientFuture,
            builder: (context, patientSnap) {
              if (patientSnap.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }
              final patient = patientSnap.data;
              if (patient == null) {
                return _BarChartCard(
                  data: List.filled(7, 0),
                  dayLabels: _dayLabels,
                  maxY: 10,
                  barColor: AppTheme.accentOrange,
                  gradientColors: [
                    AppTheme.accentOrange,
                    const Color(0xFFFB923C),
                  ],
                  tooltipSuffix: '/10',
                  yAxisLabel: _painYLabel,
                );
              }
              return FutureBuilder<Map<String, List<double>>>(
                future: PatientService.instance.getWeeklyMoodPainTrends(
                  patient.id,
                ),
                builder: (context, trendsSnap) {
                  if (trendsSnap.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  final painData =
                      trendsSnap.data?['pain'] ?? List.filled(7, 0);
                  return _BarChartCard(
                    data: painData,
                    dayLabels: _dayLabels,
                    maxY: 10,
                    barColor: AppTheme.accentOrange,
                    gradientColors: [
                      AppTheme.accentOrange,
                      const Color(0xFFFB923C),
                    ],
                    tooltipSuffix: '/10',
                    yAxisLabel: _painYLabel,
                  );
                },
              );
            },
          ),
          const SizedBox(height: 20),

          // ── Medication adherence ───────────────────────────────────────
          _SectionHeader(title: 'Medication Adherence'),
          const SizedBox(height: 10),
          FutureBuilder<PatientProfile?>(
            future: _patientFuture,
            builder: (context, patientSnap) {
              if (patientSnap.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }
              final patient = patientSnap.data;
              if (patient == null) return const SizedBox.shrink();
              return FutureBuilder<List<MedicationComplianceData>>(
                future: PatientService.instance.getWeeklyMedicationCompliance(
                  patient.id,
                ),
                builder: (context, medSnap) {
                  return _MedicationAdherenceCard(meds: medSnap.data ?? []);
                },
              );
            },
          ),
          const SizedBox(height: 20),
        ],
      ),
    );
  }

  Widget _buildNarrativeShimmer() {
    return Container(
      height: 160,
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF1D4ED8), Color(0xFF4338CA)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
      ),
      child: const Center(
        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
      ),
    );
  }

  static String _moodYLabel(double value) {
    return switch (value.toInt()) {
      1 => '😢',
      2 => '😟',
      3 => '😐',
      4 => '🙂',
      5 => '😊',
      _ => '',
    };
  }

  static String _painYLabel(double value) {
    if (value % 2 != 0) return '';
    return value.toInt().toString();
  }
}

// ── AI Narrative Loader ───────────────────────────────────────────────────────

class _AiNarrativeLoader extends StatefulWidget {
  final String patientId;
  final String patientName;
  const _AiNarrativeLoader({
    required this.patientId,
    required this.patientName,
  });

  @override
  State<_AiNarrativeLoader> createState() => _AiNarrativeLoaderState();
}

class _AiNarrativeLoaderState extends State<_AiNarrativeLoader> {
  String? _narrative;
  bool _isLoading = true;
  String? _lastPatientId;

  @override
  void initState() {
    super.initState();
    _lastPatientId = widget.patientId;
    _fetchNarrative();
  }

  @override
  void didUpdateWidget(_AiNarrativeLoader old) {
    super.didUpdateWidget(old);
    if (old.patientId != widget.patientId) {
      _lastPatientId = widget.patientId;
      _narrative = null;
      _fetchNarrative();
    }
  }

  Future<void> _fetchNarrative() async {
    if (!mounted) return;
    setState(() => _isLoading = true);

    final patientId = widget.patientId;
    final patientName = widget.patientName;

    // Step 1: fetch health data - kept outside try so fallback can use it
    PatientHealthData? health;
    int sosCount = 0;
    try {
      final results = await Future.wait([
        PatientService.instance.getTodayHealthData(patientId),
        PatientService.instance.getTodaySosCount(patientId),
      ]);
      if (!mounted || _lastPatientId != patientId) return;
      health = results[0] as PatientHealthData?;
      sosCount = results[1] as int;
    } catch (_) {
      if (mounted && _lastPatientId == patientId) {
        setState(() {
          _narrative =
              '$patientName\'s health data could not be loaded right now.';
          _isLoading = false;
        });
      }
      return;
    }

    final events = [
      'Patient: $patientName',
      if (health != null) ...[
        'Mood today: ${health.mood}',
        'Pain level today: ${health.painLevel} / 10',
        'Medications taken: ${health.medicationsTaken} of ${health.medicationsTotal}',
        if (sosCount > 0) 'SOS alerts today: $sosCount',
      ] else
        'No check-in recorded yet today',
    ];

    // Step 2: call Gemini - fall back to real data on any failure
    try {
      final narrative = await GeminiService.instance.generateDailySummary(
        patientName: patientName,
        events: events,
      );
      if (mounted && _lastPatientId == patientId) {
        setState(() {
          _narrative = narrative;
          _isLoading = false;
        });
      }
    } catch (_) {
      if (mounted && _lastPatientId == patientId) {
        setState(() {
          _narrative = _buildFallback(patientName, health, sosCount);
          _isLoading = false;
        });
      }
    }
  }

  String _buildFallback(String name, PatientHealthData? health, int sosCount) {
    if (health == null) {
      return '$name has not completed today\'s check-in yet. Remind them to log their mood and pain level.';
    }
    final pain = health.painLevel.toInt();
    final painDesc =
        pain <= 3
            ? 'low pain ($pain/10)'
            : pain <= 6
            ? 'moderate pain ($pain/10)'
            : 'high pain ($pain/10)';
    final meds =
        health.medicationsTotal > 0
            ? ' ${health.medicationsTaken}/${health.medicationsTotal} medications taken.'
            : '';
    final sos =
        sosCount > 0
            ? ' ⚠️ $sosCount SOS alert${sosCount > 1 ? 's' : ''} triggered today.'
            : '';
    return '$name checked in today feeling ${health.mood} with $painDesc.$meds$sos';
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Container(
        height: 160,
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Color(0xFF1D4ED8), Color(0xFF4338CA)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(20),
        ),
        child: const Center(
          child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
        ),
      );
    }
    return _AiNarrativeCard(narrative: _narrative!);
  }
}

// ── AI Narrative Card ─────────────────────────────────────────────────────────

class _AiNarrativeCard extends StatelessWidget {
  final String narrative;
  const _AiNarrativeCard({required this.narrative});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF1D4ED8), Color(0xFF4338CA)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF2563EB).withValues(alpha: 0.25),
            blurRadius: 20,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header row
            Row(
              children: [
                _GeminiSparkle(),
                const Spacer(),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 9,
                    vertical: 4,
                  ),
                  decoration: BoxDecoration(
                    color: Colors.white.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(
                    () {
                      final now = DateTime.now();
                      const months = [
                        'Jan',
                        'Feb',
                        'Mar',
                        'Apr',
                        'May',
                        'Jun',
                        'Jul',
                        'Aug',
                        'Sep',
                        'Oct',
                        'Nov',
                        'Dec',
                      ];
                      return '${months[now.month - 1]} ${now.day}, ${now.year}';
                    }(),
                    style: GoogleFonts.inter(
                      fontSize: 12,
                      color: Colors.white.withValues(alpha: 0.75),
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 14),

            // Narrative
            Text(
              narrative,
              style: GoogleFonts.inter(
                fontSize: 15,
                color: Colors.white,
                height: 1.65,
              ),
            ),
            const SizedBox(height: 14),

            // Footer
            Row(
              children: [
                const Icon(
                  Icons.auto_awesome_rounded,
                  color: Colors.white,
                  size: 13,
                ),
                const SizedBox(width: 5),
                Text(
                  'Generated by Gemini 2.0',
                  style: GoogleFonts.inter(
                    fontSize: 12,
                    color: Colors.white.withValues(alpha: 0.65),
                    fontStyle: FontStyle.italic,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _GeminiSparkle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.18),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withValues(alpha: 0.25)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(Icons.auto_awesome_rounded, color: Colors.white, size: 14),
          const SizedBox(width: 5),
          Text(
            'Gemini 2.0',
            style: GoogleFonts.inter(
              fontSize: 12,
              color: Colors.white,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}

// ── Weekly Stats Grid ─────────────────────────────────────────────────────────

class _WeeklyStatsGrid extends StatelessWidget {
  final String checkins;
  final String adherence;
  final String avgPain;
  final String sosAlerts;

  const _WeeklyStatsGrid({
    required this.checkins,
    required this.adherence,
    required this.avgPain,
    required this.sosAlerts,
  });

  @override
  Widget build(BuildContext context) {
    final sosInt = int.tryParse(sosAlerts.split('/').first.trim()) ?? 0;
    final adherencePct =
        int.tryParse(adherence.replaceAll('%', '').trim()) ?? 0;
    final avgPainVal = double.tryParse(avgPain.split('/').first.trim()) ?? 0;

    return Column(
      children: [
        Row(
          children: [
            Expanded(
              child: _StatTile(
                icon: Icons.check_circle_rounded,
                iconColor: AppTheme.accentGreen,
                iconBg: const Color(0xFFDCFCE7),
                label: 'Check-ins',
                value: checkins,
                sublabel: 'out of 7 days',
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: _StatTile(
                icon: Icons.medication_rounded,
                iconColor:
                    adherencePct >= 80
                        ? AppTheme.accentGreen
                        : AppTheme.accentOrange,
                iconBg:
                    adherencePct >= 80
                        ? const Color(0xFFDCFCE7)
                        : const Color(0xFFFFF7ED),
                label: 'Med Adherence',
                value: adherence,
                sublabel: adherencePct >= 80 ? 'On track' : 'Needs attention',
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            Expanded(
              child: _StatTile(
                icon: Icons.healing_rounded,
                iconColor:
                    avgPainVal <= 4
                        ? AppTheme.accentGreen
                        : AppTheme.accentOrange,
                iconBg:
                    avgPainVal <= 4
                        ? const Color(0xFFDCFCE7)
                        : const Color(0xFFFFF7ED),
                label: 'Avg Pain',
                value: avgPain,
                sublabel: avgPainVal <= 4 ? 'Low - stable' : 'Monitor closely',
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: _StatTile(
                icon: Icons.emergency_rounded,
                iconColor:
                    sosInt == 0 ? AppTheme.accentGreen : AppTheme.accentRed,
                iconBg:
                    sosInt == 0
                        ? const Color(0xFFDCFCE7)
                        : const Color(0xFFFFE4E4),
                label: 'SOS Alerts',
                value: sosAlerts,
                sublabel: sosInt == 0 ? 'All clear' : 'Review required',
              ),
            ),
          ],
        ),
      ],
    );
  }
}

class _StatTile extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final Color iconBg;
  final String label;
  final String value;
  final String sublabel;

  const _StatTile({
    required this.icon,
    required this.iconColor,
    required this.iconBg,
    required this.label,
    required this.value,
    required this.sublabel,
  });

  @override
  Widget build(BuildContext context) {
    final isDarkMode = Theme.of(context).brightness == Brightness.dark;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color:
            isDarkMode
                ? Theme.of(context).colorScheme.surface
                : AppTheme.surfaceWhite,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color:
              isDarkMode
                  ? Colors.white.withValues(alpha: 0.1)
                  : AppTheme.divider,
        ),
        boxShadow:
            isDarkMode
                ? [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.3),
                    blurRadius: 8,
                    offset: const Offset(0, 2),
                  ),
                ]
                : [],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(7),
                decoration: BoxDecoration(
                  color: iconBg,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(icon, color: iconColor, size: 16),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  label,
                  style: GoogleFonts.inter(
                    fontSize: 12,
                    color:
                        isDarkMode
                            ? Colors.white.withValues(alpha: 0.7)
                            : AppTheme.textMid,
                    fontWeight: FontWeight.w500,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            value,
            style: GoogleFonts.inter(
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color:
                  isDarkMode
                      ? Colors.white.withValues(alpha: 0.87)
                      : AppTheme.textDark,
            ),
          ),
          const SizedBox(height: 3),
          Text(
            sublabel,
            style: GoogleFonts.inter(
              fontSize: 11,
              color:
                  isDarkMode
                      ? Colors.white.withValues(alpha: 0.55)
                      : AppTheme.textMid,
              fontWeight: FontWeight.w500,
            ),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ),
    );
  }
}

// ── Bar Chart Card ────────────────────────────────────────────────────────────

class _BarChartCard extends StatefulWidget {
  final List<double> data;
  final List<String> dayLabels;
  final double maxY;
  final Color barColor;
  final List<Color> gradientColors;
  final String tooltipSuffix;
  final String Function(double) yAxisLabel;

  const _BarChartCard({
    required this.data,
    required this.dayLabels,
    required this.maxY,
    required this.barColor,
    required this.gradientColors,
    required this.tooltipSuffix,
    required this.yAxisLabel,
  });

  @override
  State<_BarChartCard> createState() => _BarChartCardState();
}

class _BarChartCardState extends State<_BarChartCard> {
  int _touchedIndex = -1;

  @override
  Widget build(BuildContext context) {
    final isDarkMode = Theme.of(context).brightness == Brightness.dark;
    return Container(
      padding: const EdgeInsets.fromLTRB(16, 20, 16, 12),
      decoration: BoxDecoration(
        color:
            isDarkMode
                ? Theme.of(context).colorScheme.surface
                : AppTheme.surfaceWhite,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color:
              isDarkMode
                  ? Colors.white.withValues(alpha: 0.1)
                  : AppTheme.divider,
        ),
        boxShadow:
            isDarkMode
                ? [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.3),
                    blurRadius: 8,
                    offset: const Offset(0, 2),
                  ),
                ]
                : [],
      ),
      child: SizedBox(
        height: 180,
        child: BarChart(
          BarChartData(
            maxY: widget.maxY,
            minY: 0,
            barTouchData: BarTouchData(
              enabled: true,
              touchCallback: (event, response) {
                setState(() {
                  if (event is FlTapUpEvent ||
                      event is FlPointerExitEvent ||
                      event is FlLongPressEnd) {
                    _touchedIndex = -1;
                  } else if (response?.spot != null) {
                    _touchedIndex = response!.spot!.touchedBarGroupIndex;
                  }
                });
              },
              touchTooltipData: BarTouchTooltipData(
                getTooltipColor:
                    (_) =>
                        isDarkMode
                            ? Colors.white.withValues(alpha: 0.87)
                            : AppTheme.textDark,
                tooltipRoundedRadius: 8,
                getTooltipItem: (group, groupIndex, rod, rodIndex) {
                  return BarTooltipItem(
                    '${rod.toY.toStringAsFixed(0)}${widget.tooltipSuffix}',
                    GoogleFonts.inter(
                      color: isDarkMode ? Colors.black : Colors.white,
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                    ),
                  );
                },
              ),
            ),
            titlesData: FlTitlesData(
              show: true,
              bottomTitles: AxisTitles(
                sideTitles: SideTitles(
                  showTitles: true,
                  reservedSize: 28,
                  getTitlesWidget: (value, meta) {
                    final i = value.toInt();
                    if (i < 0 || i >= widget.dayLabels.length) {
                      return const SizedBox.shrink();
                    }
                    final isToday = i == 3; // Thu = today (Apr 3)
                    return Padding(
                      padding: const EdgeInsets.only(top: 8),
                      child: Text(
                        widget.dayLabels[i],
                        style: GoogleFonts.inter(
                          fontSize: 13,
                          fontWeight:
                              isToday ? FontWeight.w700 : FontWeight.w400,
                          color:
                              isToday ? AppTheme.primaryBlue : AppTheme.textMid,
                        ),
                      ),
                    );
                  },
                ),
              ),
              leftTitles: AxisTitles(
                sideTitles: SideTitles(
                  showTitles: true,
                  reservedSize: 32,
                  interval: widget.maxY <= 5 ? 1 : 2,
                  getTitlesWidget: (value, meta) {
                    final label = widget.yAxisLabel(value);
                    if (label.isEmpty) return const SizedBox.shrink();
                    return Padding(
                      padding: const EdgeInsets.only(right: 4),
                      child: Text(
                        label,
                        style: GoogleFonts.inter(
                          fontSize: 11,
                          color: AppTheme.textLight,
                        ),
                        textAlign: TextAlign.right,
                      ),
                    );
                  },
                ),
              ),
              topTitles: const AxisTitles(
                sideTitles: SideTitles(showTitles: false),
              ),
              rightTitles: const AxisTitles(
                sideTitles: SideTitles(showTitles: false),
              ),
            ),
            gridData: FlGridData(
              show: true,
              drawVerticalLine: false,
              horizontalInterval: widget.maxY <= 5 ? 1 : 2,
              getDrawingHorizontalLine:
                  (_) => const FlLine(
                    color: AppTheme.divider,
                    strokeWidth: 1,
                    dashArray: [4, 4],
                  ),
            ),
            borderData: FlBorderData(show: false),
            barGroups:
                widget.data.asMap().entries.map((entry) {
                  final i = entry.key;
                  final value = entry.value;
                  final isTouched = i == _touchedIndex;

                  return BarChartGroupData(
                    x: i,
                    barRods: [
                      BarChartRodData(
                        toY: value,
                        width: isTouched ? 22 : 18,
                        borderRadius: const BorderRadius.vertical(
                          top: Radius.circular(6),
                        ),
                        gradient: LinearGradient(
                          colors:
                              isTouched
                                  ? [
                                    widget.gradientColors[1],
                                    widget.gradientColors[0],
                                  ]
                                  : [
                                    widget.gradientColors[0].withValues(
                                      alpha: 0.7,
                                    ),
                                    widget.gradientColors[1],
                                  ],
                          begin: Alignment.bottomCenter,
                          end: Alignment.topCenter,
                        ),
                        backDrawRodData: BackgroundBarChartRodData(
                          show: true,
                          toY: widget.maxY,
                          color: AppTheme.backgroundGray,
                        ),
                      ),
                    ],
                  );
                }).toList(),
          ),
        ),
      ),
    );
  }
}

// ── Medication Adherence Card ─────────────────────────────────────────────────

class _MedicationAdherenceCard extends StatelessWidget {
  final List<MedicationComplianceData> meds;
  const _MedicationAdherenceCard({required this.meds});

  double get _overallAdherence {
    if (meds.isEmpty) return 0;
    final total = meds.fold(0, (s, m) => s + m.daysTotal);
    final taken = meds.fold(0, (s, m) => s + m.daysTaken);
    return total > 0 ? taken / total : 0;
  }

  @override
  Widget build(BuildContext context) {
    if (meds.isEmpty) {
      return Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: AppTheme.surfaceWhite,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: AppTheme.divider),
        ),
        child: Center(
          child: Text(
            'No medication data available',
            style: GoogleFonts.inter(color: AppTheme.textMid),
          ),
        ),
      );
    }

    final pct = (_overallAdherence * 100).round();
    final overallColor =
        pct >= 85 ? AppTheme.accentGreen : AppTheme.accentOrange;

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppTheme.surfaceWhite,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppTheme.divider),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Overall percentage header
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text(
                '$pct%',
                style: GoogleFonts.inter(
                  fontSize: 32,
                  fontWeight: FontWeight.w800,
                  color: overallColor,
                  height: 1,
                ),
              ),
              const SizedBox(width: 8),
              Padding(
                padding: const EdgeInsets.only(bottom: 4),
                child: Text(
                  'overall this week',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    color: AppTheme.textMid,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          // Overall bar
          ClipRRect(
            borderRadius: BorderRadius.circular(6),
            child: LinearProgressIndicator(
              value: _overallAdherence,
              backgroundColor: AppTheme.divider,
              valueColor: AlwaysStoppedAnimation<Color>(overallColor),
              minHeight: 8,
            ),
          ),
          const SizedBox(height: 20),

          // Per-medication rows
          const Divider(color: AppTheme.divider, height: 1),
          const SizedBox(height: 16),
          ...meds.map((m) => _MedProgressRow(med: m)),
        ],
      ),
    );
  }
}

class _MedProgressRow extends StatelessWidget {
  final MedicationComplianceData med;
  const _MedProgressRow({required this.med});

  @override
  Widget build(BuildContext context) {
    final pct = med.daysTaken / med.daysTotal;
    final color = pct >= 0.85 ? AppTheme.accentGreen : AppTheme.accentOrange;

    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      med.name,
                      style: GoogleFonts.inter(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: AppTheme.textDark,
                      ),
                    ),
                    Text(
                      med.time,
                      style: GoogleFonts.inter(
                        fontSize: 12,
                        color: AppTheme.textMid,
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 4,
                ),
                decoration: BoxDecoration(
                  color: color.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  '${med.daysTaken}/${med.daysTotal} days',
                  style: GoogleFonts.inter(
                    fontSize: 13,
                    color: color,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          ClipRRect(
            borderRadius: BorderRadius.circular(6),
            child: LinearProgressIndicator(
              value: pct.clamp(0.0, 1.0),
              backgroundColor: AppTheme.divider,
              valueColor: AlwaysStoppedAnimation<Color>(color),
              minHeight: 7,
            ),
          ),
        ],
      ),
    );
  }
}

// ── Section Header ────────────────────────────────────────────────────────────

class _SectionHeader extends StatelessWidget {
  final String title;
  const _SectionHeader({required this.title});

  @override
  Widget build(BuildContext context) {
    return Text(
      title,
      style: GoogleFonts.inter(
        fontSize: 17,
        fontWeight: FontWeight.w700,
        color: AppTheme.textDark,
      ),
    );
  }
}
