// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUcBVuoHkqFf5f9YU5tXNiUgEntmmjaXU',
    appId: '1:631057330468:web:62aa3e016e18b0833a83b1',
    messagingSenderId: '631057330468',
    projectId: 'caresync-vertex',
    authDomain: 'caresync-vertex.firebaseapp.com',
    storageBucket: 'caresync-vertex.firebasestorage.app',
    measurementId: 'G-3ZV4PRP8B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASQDBqeevmBKM6AlJLASy0Rhczu6DEfI',
    appId: '1:631057330468:android:a58e5165bc844ee73a83b1',
    messagingSenderId: '631057330468',
    projectId: 'caresync-vertex',
    storageBucket: 'caresync-vertex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZsKDqzpXrgtdQrOMvOb77Q2vTONgFcg',
    appId: '1:631057330468:ios:b332b6e6823f79473a83b1',
    messagingSenderId: '631057330468',
    projectId: 'caresync-vertex',
    storageBucket: 'caresync-vertex.firebasestorage.app',
    iosBundleId: 'com.caresync.caresyncAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE3hE0pcYq3iLKbI4xaquQxyHzyOcMsY4',
    appId: '1:631057330468:web:b6b90a029c9199d53a83b1',
    messagingSenderId: '631057330468',
    projectId: 'caresync-vertex',
    authDomain: 'caresync-vertex.firebaseapp.com',
    storageBucket: 'caresync-vertex.firebasestorage.app',
    measurementId: 'G-Z1LSJX9CH0',
  );
}